### PR TITLE
Automatic dashboard import on install

### PR DESCRIPTION
**Pull request by daniellee**
Hi, I work at Raintank and @mattttt asked me to take a look the new Percona App. It's really exciting to see a new app! It looks great and we could go live as is but after a quick review we came up with the following small changes.

For the worldPing app, we have a feature where it automatically imports dashboards after the user clicks the _Enable_ button on the plugin config page. The Percona App has a lot of dashboards so I thought this would help make the installation smoother:

percona

There are two other changes included in this PR:
- Cleanup of unused css and html
- Adds the text _| Percona App_ to each dashboard title. There is no way of grouping dashboards in Grafana other than with tags and titles. The percona tag already exists for every dashboard but the titles are very generic and easy to mix up with other dashboards. I added them at the end of the title (you could also prefix the titles with Percona App instead).

### CODE REVIEW

**Comment by roman-vynar** [comment]
@daniellee fantastic, thanks for the cleanup. Also I wanted to ask about auto-import but I had some issue and it was re-importing each time I was visiting App page.

One thing about dashboards, it looks like your editor applied unnecessary changes because of the way it works. I am using a script to dump all the dashboards from Grafana and do the cleanup. So once I update those dashboards we will end up with another big diff. Let me merge this PR and commit title changes again.

**Comment by daniellee** [comment]
@roman-vynar sorry about messing up the dashboards. Looks like you're ready with the dashboard changes. If it's ok with you, then I'll publish the app to grafana.net now?

**Comment by roman-vynar** [comment]
@daniellee I think we are good now to publish. Thanks!

**Comment by daniellee** [comment]
@roman-vynar published! https://grafana.net/plugins/percona-percona-app

**Comment by roman-vynar** [comment]
🍻 Awesome, thanks for a quick turnaround and doing great stuff!

**Pull request merged**
